Profiles
redhat-beyond/Pro4U pull request #113
Opened 2023-05-16 17:02 UTC by TalReinfeld

Adding all the profile aspects

profile:
- profile.html - a base html.
- test_profile - get_profile for getting the profile page of the entity

client/professional:
- professional/client_profile.html - extends the profile.html
- test_professional/client - including 4 tests
- professional/client_urls - including the profile path for the profiles pages
- professional/client_views - including the request to the profile page

2023-05-16 17:30 UTC, OfirBachar commented
> Adding all the profile aspects
> 
> profile:
> 
> * profile.html - a base html.
> * test_profile - get_profile for getting the profile page of the entity
> 
> client/professional:
> 
> * professional/client_profile.html - extends the profile.html
> * test_professional/client - including 4 tests
> * professional/client_urls - including the profile path for the profiles pages
> * professional/client_views - including the request to the profile page

Can you add a png file so we can see it more easily

2023-05-16 17:58 UTC, idoyek commented on account/tests/urls_tests/test_profile.py
What is this file for? When I ran all of your current tests it wasn't included

2023-05-16 18:04 UTC, TalReinfeld commented on account/tests/urls_tests/test_profile.py
Instead of code duplicate, the test_professional and the test_client are using methods from there
for example in test_get_client_profile, i use it in this line :
response = TestProfileViews.get_profile(client=client, entity_id=test_client.client_id, url=BASE_URL)

2023-05-16 18:04 UTC, TalReinfeld commented
> > Adding all the profile aspects
> > profile:
> > 
> > * profile.html - a base html.
> > * test_profile - get_profile for getting the profile page of the entity
> > 
> > client/professional:
> > 
> > * professional/client_profile.html - extends the profile.html
> > * test_professional/client - including 4 tests
> > * professional/client_urls - including the profile path for the profiles pages
> > * professional/client_views - including the request to the profile page
> 
> Can you add a png file so we can see it more easily

Done @OfirBachar

2023-05-16 19:09 UTC, idosinger98 approved these changes

2023-05-16 20:19 UTC, patrisiakaplun commented on account/tests/urls_tests/test_profile.py
> +FAKE_ID = 10000000
I don't see that it has any use in the file..

2023-05-16 20:23 UTC, patrisiakaplun commented on account/tests/urls_tests/test_profile.py
> +FAKE_ID = 10000000
I see that you use FAKE_ID only in test_professional.py and not in this file..
Consider moving it there..

2023-05-16 21:40 UTC, guybeckenstein approved these changes
LGTM

2023-05-17 06:28 UTC, Yarboa requested changes
Tests are messy, see my comments 
Please do not answer with questions, currently, tests are written wrong for pytest-django

2023-05-17 06:28 UTC, Yarboa commented on account/tests/urls_tests/test_client.py
> +        test_client = demo_client
the fixture already holds everything in demo_client

2023-05-17 06:28 UTC, Yarboa commented on account/tests/urls_tests/test_client.py
> +        response = TestProfileViews.get_profile(client=client, entity_id=test_client.client_id, url=BASE_URL)
Please explain this, I assume it should not be here

2023-05-17 06:28 UTC, Yarboa commented on account/tests/urls_tests/test_client.py
> +class TestClientViews:
Whats does this class aims to do? 
Test view? test UI through client, 
I think you should organize things here

2023-05-17 06:28 UTC, Yarboa commented on account/tests/urls_tests/test_client.py
> +    def test_show_profile_non_existent_client(self, client, demo_client):
same here, I do not understand why do you need it
You should call HTTP requests through client fixture
sorry

2023-05-17 06:47 UTC, idosinger98 requested changes
Why do we need to sign up when the user is already logged in? Please remove it

2023-05-17 07:34 UTC, TalReinfeld commented
> Tests are messy, see my comments Please do not answer with questions, currently, tests are written wrong for pytest-django

@Yarboa 
Done

2023-05-17 10:37 UTC, idosinger98 approved these changes
LGTM

2023-05-17 16:53 UTC, idoyek approved these changes
LGTM

2023-05-17 16:54 UTC, OfirBachar approved these changes
LGTM

2023-05-18 07:36 UTC, Yarboa approved these changes
LGTM

2023-05-18 15:09 UTC, merged