Profile details
redhat-beyond/Pro4U pull request #114
Opened 2023-05-16 22:43 UTC by TalReinfeld

Adding a html file (profile_details) that extends profile.html,
the file show all the profile details.

Adding a test to check the inheritance between profile_details.html
and profile.html.

@dependabot
This pull request is depends on PR #113

2023-05-18 17:49 UTC, idoyek approved these changes
LGTM

2023-05-21 08:42 UTC, guybeckenstein approved these changes
LGTM

2023-05-21 09:07 UTC, idosinger98 approved these changes
LGTM

2023-05-21 12:06 UTC, Yarboa requested changes
Please review comments
You do not assert the content of the rersponses

2023-05-21 12:06 UTC, Yarboa commented on account/views/client_views.py
> +    return render(request, 'account/profile_details.html', {'client': client, 'profile': profile})
This parameter could be retrieved through
 response.context.get("client")
 response.context.get("profile")

2023-05-24 11:12 UTC, idosinger98 requested changes
Please use base.html

2023-05-28 17:13 UTC, TalReinfeld commented
> Please use base.html

@idosinger98 Done

2023-05-28 17:17 UTC, idosinger98 reviewed
please convert to draft

2023-05-28 17:17 UTC, idosinger98 reviewed
please convert to draft

2023-06-07 11:14 UTC, Yarboa commented
I think you need to rebase

2023-06-08 12:44 UTC, Yarboa approved these changes
LGTM

2023-06-08 12:44 UTC, merged