updating chat.css and message.html
redhat-beyond/Pro4U pull request #130
Opened 2023-05-27 21:53 UTC by patrisiakaplun

Adapting the design of the chat to the site template and adding functionality that allows entering the chat in the recent chats bar.

2023-05-28 06:15 UTC, idosinger98 approved these changes
LGTM

2023-05-28 12:03 UTC, guybeckenstein approved these changes
LGTM

2023-05-28 13:08 UTC, Yarboa requested changes

2023-05-28 13:08 UTC, Yarboa commented on chatmessage/templates/chatmessage/message.html
> +      <a href="http://127.0.0.1:8000/chatmessage/{{ user }}/{% if sender_type == 'P' %}{{ contact.professional_id }}{% else %}{{ contact.client_id }}{% endif %}/{{ sender_type }}/">
Could not be used in production

2023-05-28 21:58 UTC, patrisiakaplun commented on chatmessage/templates/chatmessage/message.html
> +      <a href="http://127.0.0.1:8000/chatmessage/{{ user }}/{% if sender_type == 'P' %}{{ contact.professional_id }}{% else %}{{ contact.client_id }}{% endif %}/{{ sender_type }}/">
done.

2023-05-29 13:46 UTC, idosinger98 approved these changes
Lgtm

2023-05-29 14:02 UTC, guybeckenstein approved these changes
LGTM

2023-05-29 16:26 UTC, Yarboa approved these changes
LGTM

2023-05-29 16:26 UTC, merged