Adding contribution file
redhat-beyond/Pro4U pull request #16
Opened 2023-03-21 13:41 UTC by OfirBachar

Adding contribution.md file

2023-03-21 13:53 UTC, patrisiakaplun approved these changes
LGTM

2023-03-21 18:21 UTC, idoyek approved these changes
LGTM

2023-03-22 10:25 UTC, Yarboa requested changes

2023-03-22 10:25 UTC, Yarboa commented on contribution.md
> +* Please note that Pytest is already installed in this project's virtual environment.
No pytest here, at this status

2023-03-22 10:25 UTC, Yarboa commented on contribution.md
> +## Pull request template:
Template is not important

You should describe what should be in the description

2023-03-22 10:25 UTC, Yarboa commented on contribution.md
> +4.	Ask cotributors to review your PR.
Consider this, (please make it more friendly)

Create PR
1) Clear subject
2) Clear description, 
3) AddResolve #Issue
4) Assign PR to yourself

2023-03-22 10:25 UTC, Yarboa commented on contribution.md
> +5.	Once you have the sign-off of two developers and one of the maintainers, your PR will be merged.
Consider the foolowing
move to -> \#\# Review Process

And describe the minimum for fast attention 
1) Verify Githab actions tests status = PASSED
2) Select Reviewers under Reviewers section

Note: at least 2 LGTM, Approves needed for Core reviewers to review

2023-03-22 10:25 UTC, Yarboa commented on contribution.md
> +## Reviewing PRs:
Please also explain the difference between Reviewers and CoreReviers

2023-03-22 15:00 UTC, OfirBachar commented on contribution.md
Deleting unnecessary lines/spaces

2023-03-23 07:40 UTC, patrisiakaplun approved these changes
LGTM

2023-03-23 07:51 UTC, TalReinfeld approved these changes
LGTM

2023-03-23 08:14 UTC, OfirBachar reviewed
LGTM

2023-03-23 12:06 UTC, Yarboa reviewed
Once you changed 
1. Reviewers
2.  The Maintainers 

Please use it in the whole doc.
Please replace mentors with something like this 

https://github.com/redhat-beyond/Pro4U/pull/16#discussion_r1145285200

2023-03-23 12:41 UTC, idosinger98 approved these changes
LGTM

2023-03-23 14:48 UTC, Yarboa commented on contribution.md
> +**Note: at least 2 LGTM, Approves needed for Core reviewers to review**
I still see it, Please change Core reviewers to maintainers

2023-03-23 14:48 UTC, Yarboa commented on contribution.md
> +2.  The Maintainers are feedback given by the mentors.
consider change to this 
are project maintainers
They are final decision makers on which portions of source code go into a build or release

I think this should move to before "Create PR"

2023-03-24 06:46 UTC, idosinger98 approved these changes
LGTM

2023-03-24 07:49 UTC, OfirBachar reviewed
LGTM

2023-03-24 09:30 UTC, TalReinfeld approved these changes
LGTM

2023-03-24 10:32 UTC, brochwerger commented on contribution.md
> +**Note: for fast maintainers review please refer Reviewing PRs**
Keep terminology consistent - stick to "Reviewers" and "Maintainers", no "fast reviewers")

2023-03-24 10:34 UTC, brochwerger commented on contribution.md
> +**Note: at least 2 LGTM, Approves needed for Maintainers to review**
not clear - did you mean two LGTM and two approvals from Reviewers before Maintaners review ?

2023-03-24 11:18 UTC, TalReinfeld approved these changes
LGTM

2023-03-24 11:50 UTC, idosinger98 approved these changes
LGTM

2023-03-24 12:33 UTC, guybeckenstein commented on contribution.md
> +5. Go to http://localhost:8000 in your web browser
Note that it is also possible to enter the website using http://127.0.0.1:8000/, but I don't find this note mandatory

2023-03-24 12:33 UTC, guybeckenstein approved these changes

2023-03-26 05:07 UTC, Yarboa approved these changes

2023-03-26 05:08 UTC, merged