Created Pro4U updated landing page
redhat-beyond/Pro4U pull request #83
Opened 2023-05-05 21:13 UTC by guybeckenstein

1. Removed unnecessary files:
   - `models.py` and `migrations/*.py`, there is NO logic in this app!
   - icons from `static/img`
2. Renamed `landing/templates/html/` to `landing/templates/landing`.
3. Created an updated landing homepage for Pro4U which shows professionals for guests & registered users.
4. Designed **HTML** files within `landing/templates/html/` using **CSS, JavaScript** within `static`.
   - Javascript file was used to enable the _attribute-class:show_ option within the **CSS** file.
5. Updated `Pro4U/urls.py` after renaming.
6. Created a new method within `account.models.professionals.py` called `get_avg_rating` to show average rating for each professional entity in homepage.
7. Added TODOs where relevant

1. A guest/user can see up to 48 randomly-shuffled professionals. Each professional has a full name, city, profession, average rating and image. Showing image is not implemented, so we use a default image 'NO IMAGE AVAILABLE' for each professional without image.
2. A guest can sign up/log in. Sign up and log in templates are not implemented.
3. A guest can search a professional. Search logic is not implemented.

2023-05-06 16:04 UTC, idosinger98 reviewed
Good job. Only if you can put a professional in the admin and show us how you display his pictures and how when I click on him it takes me to his home page (even make the pro a simple home page that seems to work)

2023-05-07 10:19 UTC, TalReinfeld commented on landing/views.py
> +            professional.avg_rating = round(professional.avg_rating, 2)
I think that its more correct to round it with only 1 digit after the point
I believe that it works like that:
professional.avg_rating = round(professional.avg_rating, 1)

2023-05-07 12:42 UTC, TalReinfeld commented
It failed in the PyTest...

2023-05-09 05:33 UTC, Yarboa commented
> It failed in the PyTest...

Please remove labels in case status moved to Draft,

2023-05-09 05:35 UTC, Yarboa commented
> It failed in the PyTest...

Please take a look here 
https://github.com/redhat-beyond/Pro4U/actions/runs/4907225025/jobs/8762214599?pr=83#step:6:371-373

2023-05-09 05:40 UTC, Yarboa requested changes

2023-05-09 05:40 UTC, Yarboa commented on landing/tests/tests.py
> +from django.test import Client
It is not the correct way to use client fixtures in pytest
Please take a look here
https://pytest-django.readthedocs.io/en/latest/helpers.html#id2

Do not confuse with this 
https://docs.djangoproject.com/en/4.2/topics/testing/tools/

Read the pytest-django docs, it is wrapping the django-test client

2023-05-10 17:11 UTC, Yarboa commented on landing/templates/landing/base.html
> +  <head>
you have too many css files,
Once working with boostrap, most of css changes done through bootstrap
less css files please

2023-05-18 15:06 UTC, Yarboa commented on landing/templates/landing/base.html
> +  <head>
I will not die on that hill
but all of the css staff making the code non readable

2023-05-18 15:08 UTC, Yarboa approved these changes
LGTM

2023-05-18 15:08 UTC, merged